spring.datasource.url=jdbc:mysql://localhost:3306/agri_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=sjk1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# ??Session????30????????
server.servlet.session.timeout=1800
